requires 'perl' => '5.008001';
requires 'Carp';
requires 'Class::Tiny::Chained';
requires 'Digest::SHA';
requires 'Encode';
requires 'List::Util' => '1.29';
requires 'MIME::Base64';
requires 'Role::Tiny' => '2.000000';
requires 'URI';
requires 'URI::Escape';
requires 'URI::QueryParam';
